# Guardar y recuperar un modelo de un fichero binario pickle

1. Guardar modelo en un fichero
2. Crear un nuevo modelo con los datos del fichero
3. Utilizar el nuevo modelo 

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import matplotlib.pyplot as plt
import seaborn as sns

flores=sns.load_dataset('iris')
from sklearn.model_selection import train_test_split
X=flores.drop(('species'), axis=1)
y=flores['species']
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.3)

from sklearn.svm import SVC
modelo=SVC(gamma='auto')
modelo.fit(X_train,y_train)
predicciones=modelo.predict(X_test)

from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, predicciones))
print(classification_report(y_test, predicciones))


[[14  0  0]
 [ 0 17  0]
 [ 0  0 14]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        14
  versicolor       1.00      1.00      1.00        17
   virginica       1.00      1.00      1.00        14

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [2]:
import pickle


In [4]:
#La parte de modelo que es el que entrenamos lo guardamos en un fichero pickle
#modelo.pickle sera el fichero, intentamos abrirlo en forma escritura binaria, de ahí el wb
with open("modelo.pickle", "wb")as file:
    pickle.dump(modelo, file)

In [5]:
# Ahora leemos del fichero pickle y lo vamos a guardar en un avariable que llamaremos modelo2
#Lo abrimos en forma lectura binaria
with open('modelo.pickle', "rb") as file:
    modelo2=pickle.load(file)


In [6]:
predicciones=modelo2.predict(X_test)

from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, predicciones))
print(classification_report(y_test, predicciones))


[[14  0  0]
 [ 0 17  0]
 [ 0  0 14]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        14
  versicolor       1.00      1.00      1.00        17
   virginica       1.00      1.00      1.00        14

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [7]:
# Como el modelo ya estaba entrenado hemos sido capaces de recuperandolo de un fichero usarlo.